ros-infrastructure/rep

rep-0103.rst
Not sure what the `Post-History` tag is all about, but other REPs seem to use it as a last-changed date.
@tfoote to review.
=> Add Mike Purvis as author to 103, change date.

rep-0003.rst, rep-0142.rst
These are the proposed platforms and minimum requirements for ROS Jade Turtle.
This pull request also updates the language in REP-142 to be inclusive of releases after Indigo, including Jade.
=> Update to REP-0003 for ROS Jade Turtle

rep-0144.rst
Hi, before I send that to ros-users, I'd like some early feedback as I believe I forgot some specific package types and the versioning is probably not in sync with what our infrastructure can handle.
=> REP about package naming conventions

rep-0142.rst
Also clarifying title. 
There's only one small change so calling it out as a diff instead of duplicating the document.
=> updating 142 for jade metapackage updates

rep-0120.rst
=> REP-120: fix minor typos.

rep-0147.rst
This is a new REP to support standardizing messages for interacting with aerial vehicles.
=> First draft of standard interfaces for aerial vehicles. [REP 147]

rep-0127.rst, rep-0140.rst
=> update information about orphaned packages

rep-0142.rst
Connects to https://github.com/ros/metapackages/pull/14 and https://github.com/ros/metapackages/issues/13 .
=> Move urdf_tutorials to desktop_full

rep-0128.rst
=> Catkin ignore example

rep-0142.rst
=> Fix up minor typos in REP 142.

rep-0003.rst
See: https://github.com/ros-infrastructure/rep/pull/93#discussion_r161031157
=> fix typo in REP-0003

rep-0111.rst
Specifies the proposed implementation of ros-infrastructure/rosdep#573.
@ros-infrastructure/ros_team Please provide feedback on this soon in order to ask for feedback from the whole community on discourse.
=> Rep111 wildcard

rep-0149.rst
Add a bit of language into the "Environment Variables" section to describe the new ROS_PYTHON_VERSION being proposed in https://github.com/ros/ros_environment/pull/4
=> Rep 149 add ros python version

rep-0149.rst
The REP has been in draft state for ~9 months. Even though we don't have an implementation of the compatibility version yet I would like to move forward and finalize it.
Once this has been approved and merged I will go ahead and upload the authoritative schema to http://download.ros.org/schema in order to make it possible to validate manifest files following version 3.
=> mark REP 149 as final

rep-2001.rst
Draft of ROS 2 Bouncy and newer variants to document the work being done at https://github.com/ros2/variants/pull/1
=> REP-2001 ROS 2 Variants initial draft

rep-2000.rst
https://answers.ros.org/question/315686/what-revision-of-c-is-targeted-by-ros-2/
=> mention C11 as minimum language requirement

xsd/package_common.xsd, xsd/package_format1.xsd, xsd/package_format2.xsd, xsd/package_format3.xsd
Signed-off-by: Dan Rose <dan@digilabs.io>
=> Fix typos in xsd documentation

rep-0147.rst
=> rep147: fix minor typo.

rep-0153.rst
This is a redo of #214 but updating REP 153 instead.
=> add test_abi to REP 153

rep-0147.rst
Adding Vehicle status proposed message
=> REP 147: VehicleStatus

rep-2005.rst
as per title
Signed-off-by: Karsten Knese <karsten.knese@us.bosch.com>
=> add diagnostics

rep-2005.rst
Signed-off-by: Chris Lalancette <clalancette@gmail.com>
=> Add in some additional packages.

rep-2005.rst
Signed-off-by: Karsten Knese <karsten.knese@us.bosch.com>
=> add laser_proc

rep-html-template
This should help #222
Signed-off-by: Tully Foote <tfoote@osrfoundation.org>
=> Defer mermaid.js loading until end of body

rep-0147.rst
See http://build.ros.org/job/doc_independent-packages/285/console.
=> fix linter warning in REP 147

.travis.yml, Makefile, doc/Makefile
Part of resolving ros-infrastructure/rep#239.
=> use Python 3 to generate documentation

rep-0128.rst
=> Correct typo

rep-0128.rst
=> Fix sentence structure

rep-2005.rst
These repos were previously [proposed for addition](https://github.com/ros-infrastructure/rep/pull/225#discussion_r382452254) with some endorsement and no objections. Their being left out was an oversight on my part. Unless there are objections now, I'll go ahead and merge this change.
=> add ign and webots repos

rep-0119.rst
Otherwise there is a rendering error in REP-0000:
=> fix authors list

rep-0119.rst
=> Fix small typo in 119.

xsd/package_format3.xsd
=> add missing characters to condition regex

xsd/package_format3.xsd
While looking at #284...
Update the `condition` regex for `ConditionalType` in the same way as for `DependencyType` in #275.
=> also update pattern for ConditionalType

rep-2004.rst
@maryaB-osr can you please take a look? After we iterate on it, I can ask for feedback more broadly.
=> [REP-2004] add to the motivation to address common questions

rep-2005.rst
This PR adds the relevant Micro XRCE-DDS repos to the REP-2005, which includes the common packages of ROS 2, that is, those packages of the ROS 2 ecosystem that are widely used, actively maintained, and of sufficient quality to be relied upon.
The addition of the Micro XRCE-DDS packages comes along with the inclusion of the micro-ROS packages (see [PR #290](https://github.com/ros-infrastructure/rep/pull/290) for reference), being the former the default middleware implementation of the latter. Below, we detail why we deem these packages worthy to be added and responding to the requirements set by the REP-2005 description.
**Scope:**
- *Open source:* All packages of Micro XRCE-DDS come under Apache 2.0 license just as the core package of ROS 2.
- *Connected to the ROS 2 project:* the Micro …
=> Adds Micro XRCE-DDS repos to REP-2005

rep-2000.rst
=> Galactic REP-2000 update to new connext RMW.

rep-2005.rst
Justification:
* This sets the guidelines for the rest of the packages listed in here, contributions to it have high impact
=> Add REP source repository to REP-2005

rep-2001.rst
I used [a script](https://github.com/audrow/open-robotics-scripts/blob/main/get-variants/index.ts) to generate most of the information for the variants REP.
=> Add all variants for REP 2001

rep-2000.rst
=> Fix a warning that is being shown in REP-2000.

rep-2000.rst
Do general cleanup of the section, aiming for a better flow and
more clarity.  Also add some language saying that we *may*
support other releases as Tier 3.  No real changes to the
support or release schedule.
=> Update the language in the Release Schedule.

rep-2000.rst
This updates rolling's target to be Humble Hawksbill.
=> Update rolling target

rep-2007.rst, rep-2009.rst
They have both been implemented.
=> Set REP-2007 and REP-2009 as Final.

rep-2001.rst
This PR adds Humble. I also fixed a warning with a section title in Rolling.
=> Add Humble to REP 2001

rep-0147.rst
Following #120 
This PR is for visibility of ongoing proposals and available for comment.
=> Continuing review of REP 147

rep-2001.rst
Via https://github.com/ros2/variants/pull/37
Unclear whether I should add it to all the other active variants as well as rolling.
=> [REP-2001] Add Dev Tools Variant

rep-2001.rst
=> Add Iron Irwini to the REP-2001 document.

rep-0147.rst
Update/improve REP-147 with some minor changes or errors. 
* Add as2_msgs
* Specify base variable name in enums
* Clarify timestamping for some messages
* Add missing package for Header in messages
* Ran spellcheck and fixed all errors
=> Add minor updates to REP-147

rep-2005.rst
Hold in draft: to be voted on during April 8, 2025 ROS PMC meeting.
=> Add rmw_zenoh to REP 2005

rep-2000.rst
=> Update Rolling to point to Kilted Kaiju in REP 2000
