ros-infrastructure/rep

rep-0003.rst
In the first commit I cleaned up the style, correctly using nested lists to make it cleaner looking. In the second I made the use of `build farm` versus `buildfarm` consistent in the document.
Finally I added some comments about C++11 compatibility to the REP, as discussed here:
https://github.com/ros-infrastructure/rep/pull/89#issuecomment-70164063
=> rep-0003: update to mention C++11 compatibility

rep-0143.rst
Since the original announcement on Nov 29th 2014 the received comments have been processed:
* https://github.com/ros-infrastructure/rosdistro/pull/45
* https://github.com/ros-infrastructure/rep/pull/87
Before rolling REP 143 out into the main rosdistro repo (which is required before we can roll out the new build farm) the REP should be marked final.
@esteve @tfoote @wjwwood Please approve.
=> mark REP 143 final

rep-0140.rst
From http://answers.ros.org/question/220135/what-is-the-purpose-of-the-architecture_independent-tag/
It is now in use, and adding more example details.
=> make arch_independent description more accurate

rep-0008.rst
There have been some changes to how we distribute and organize Python code for ROS packages with catkin. This pull request attempts to update the REP to capture the differences where appropriate.
@tfoote @esteve @dirk-thomas
=> Update to REP-0008 to include catkin's Python conventions

rep-0142.rst
The ros-desktop metapackage now only contains tutorials and roslint (which should probably go somewhere like core or base). So in principal we could rename this to ros-tutorials and ros-desktop-full to ros-desktop, but that's probably to late in the game...
=> [REP 142] Remove superfluous dependencies from desktop (already in viz)

rep-0001.rst
To lists.ros.org instead of code.ros.org
=> fix ros-users mailing address

rep-0003.rst
I've updated the requirements for Kinetic Kame. @scpeters has expressed interest in ROS having support for C++11 for better compatibility with newer versions of SDFormat. I don't know if the version of Gazebo should be 5 or 6, and the list of C++11 features will be expanded as we see if they can benefit our users (e.g. lambdas for subscriptions, `std::shared_ptr` instead of boost's)
=> Update to REP-0003 for ROS Kinetic Kame

rep-0003.rst
Because support for Qt4 has ended, we propose migrating rqt and rviz to Qt5 in Kinetic.
This will affect maintainers of rviz and rqt plugins, who will need to update their code to Qt5.
We do not expect the Qt4 -> Qt5 migration to require significant code changes.
See the Qt Wiki for a migration guide: https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5
For PyQt4/PyQt5, see: http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html
Note that Kinetic will also support Gazebo 7, which still uses Qt4. (Qt5 migration is targeted for Gazebo 8) We have started experimenting with Qt5 migration in rqt and rviz and have confirmed the following:
* Qt4 and Qt5 can be installed on the same machine without package conflicts
* Gazebo 7 (which is linked against Qt4) can run side-by-side with Rviz linked …
=> Add Qt 5 requirement to ROS Kinetic

rep-0142.rst
This adds `genjs` as a core ROS package for Kinetic:
https://github.com/RethinkRobotics-opensource/genjs
This will be used with `rosjs` Javascript ROS client library:
https://github.com/RethinkRobotics-opensource/rosjs
=> updating 142 to add gennodejs as kinetic ros_core pkg

rep-html-template
seesaw is used heavily on the wiki but is not and should not be used in the REPs
=> remove unused seesaw javascript

rep-0003.rst
As per subject.
Probably copied from the *For both catkin and rosbuild packages [..]* bullet point above it.
=> Remove copy/pasta 'for' in Hydro & Indigo platform descriptions

rep-0127.rst, rep-0140.rst, xsd/package_common.xsd, xsd/package_format1.xsd, xsd/package_format2.xsd
Fixes #77.
Since validators have issues with relative includes inlined schemas are also available via:
* ~~http://download.ros.org/package_format1.xsd~~
* ~~http://download.ros.org/package_format2.xsd~~
* http://download.ros.org/schema/package_format1.xsd
* http://download.ros.org/schema/package_format2.xsd
Since these URLs might be embedded into package manifests please carefully review them since we can't change them after the fact.
=> add schema files for REP 127 and 140

rep-0003.rst
These are the platforms for which bloom does a best effort to generate targets. https://github.com/ros/rosdistro/blob/master/kinetic/distribution.yaml#L5-L13
Follow up to https://github.com/ros/rosdistro/pull/12464#issuecomment-254027959
=> Add references to Debian Jessie and Fedora 23 24

rep-0003.rst
The rendered versions of the current state of this PR can be seen here: https://github.com/ros-infrastructure/rep/blob/rep3_lunar/rep-0003.rst#lunar-loggerhead-may-2017---may-2019
=> Update REP3 for ROS Lunar Loggerhead

rep-0127.rst, rep-0140.rst
Updating REP 127 with the implementation changes proposed in https://github.com/ros-infrastructure/catkin_pkg/pull/162.
Recognizing that the standard was already released, these are structured as an optional add-on rather than a new implementation requirement.
=> Add optional package name exemptions.

docutils_transforms_reps.py
As per subject.
Seemed strange to have that `12` there, as other places in this class do use templates / constants for this sort of thing.
=> Remove magic nr in content-type url generation.

docutils_transforms_reps.py
As per subject.
Links to REPs in REP headers didn't include `.html`, making links (except those to `.rst` source files) `404`.
=> Add '.html' extension to rep_url template var to make header links work

rep-0149.rst, xsd/package_format3.xsd
Opening this draft for reference purposes. The goal is to cover:
* group dependencies #141
* ABI / compatibility version #142
* conditional dependencies (e.g. across ROS 1 and ROS 2) #143
In order to not mix the discussion on the different subjects I have created three separate issues. Please comment on the referenced issues for topic specific feedback.
=> REP 149: Package Manifest Format Three Specification

rep-0149.rst
Based on the feedback in #138. While we might not want to recommend using these operators for comparing the ROS distro name (since they will "wrap" in the future) we will provide the operators. So the user can choose if / what they want to use it for.
=> add more operators to conditions

rep-0149.rst
Until now it was unclear where the new environment variables would come from which should be used for the conditions. This patch adds a subsection to clarify that a new ROS package named `ros_environment` will be introduced in both ROS versions.
@ros-infrastructure/ros_team Please provide feedback to the current draft and feel free to fix / improve spelling / wording where you see fit and propose concrete additions if you think more information / context would be helpful.
=> add subsection about new ROS package ros_environment

rep-0151.rst
Following discussion in #149, a proposal for migrating Python in ROS 1 without either a hard cutover or a whole second set of Debian packages.
=> Bilingual Python proposal

rep-0003.rst, rep-0100.rst, rep-0107.rst, rep-0131.rst, rep-0133.rst, rep-0142.rst, rep-0150.rst
This is a REP meant to supplant REP-142, mainly to remove `robot_model` from the Melodic metapackages.  This should essentially complete ros/robot_model#195.
=> Add in REP-150: updated metapackages for ROS Melodic

rep-0142.rst
In particular:
1.  Remove "extends" from "ros_core" definition, since extends
is meant to be used for other meta-packages.
2.  Add "ros" and "ros_comm" into "ros_core" package list.
3.  Remove "console_bridge" from "ros_core" packages, since
it is provided by the system since Trusty (Indigo).
4.  Move "angles" from "ros_base" to "desktop", since it is
a dependency of common_tutorials.
5.  Make viz extend from "ros_base" instead of "robot".
=> Update REP-142 with some fixes found during REP-150 review.

rep-0142.rst
desktop_full currently "extends" urdf_tutorials, which is wrong
in two ways:
1.  "extends" should be used for meta-packages, not for packages,
and thus this should be a package on desktop_full.
2.  The name is not "urdf_tutorials", but instead "urdf_tutorial".
Fix both of these.
=> One more fix to REP-142.

rep-0136.rst
It seems that since the time this article was written, `run_depend` has been deprecated in favor of `exec_depend`, so it might helpful for new package maintainers to be instructed to use `exec_depend` instead of `run_depend`.
I'm not clear on whether we're permitted to revise these REPs, so feel free to reject this PR if this isn't the accepted procedure for this.
=> Update to add recommendations for format 2

rep-0149.rst
Hi,
I would like to propose adding an optional file attribution to the license tag in REP 149.(#156,https://github.com/ros-infrastructure/bloom/issues/456). As I'm not familiar with REP, I would appreciate if you review the format first.
When the format is OK, I will call out for review to the discource.
The affected packages will be
* https://github.com/ros-infrastructure/catkin_pkg (package.xml parser for ROS1)
* https://github.com/ament/ament_package (package.xml parser for ROS2)
* https://github.com/ros-infrastructure/bloom (tool for binary packaging)
And I will provide PRs for the three.
Thanks is advance.
=> REP 149: Add file attribution to license tag

rep-0003.rst
Qt5 now 5.9.5: https://packages.ubuntu.com/bionic/qtbase5-dev
PyQT now 5.10.1 https://packages.ubuntu.com/bionic/pyqt5-dev
=> [melodic] REP3: update qt versions for bionic

rep-0150.rst
See ros/rosdistro#17919.
Separating `rosconsole` and moving `pluginlib` and `class_loader` from "ros_base" to "ros_core".
=> separate rosconsole

rep-0149.rst
This PR proposes changes to rep-149 to use the `condition` attribute as a way of making a package work in both ROS 1 and ROS 2.
* adds `condition` attribute on the build type
* updates section `Dependencies across ROS 1 and ROS 2` to say a package can condition themselves on an environment variable `ROS_VERSION`.
=> Use condition attribute on build_type

rep-0103.rst
The word "desireable" is spelled incorrectly.
Closes https://github.com/ros-infrastructure/rep/issues/178#issue-372642473
=> Fixed spelling mistake in REP 103

rep-0153.rst
Related to ros2/ros_buildfarm_config#12.
Since the major ROS version is specific to a distribution it should be annotated in the index file (rather than in the buildfarm configuration).
The current implementation would fail to parse newer files containing the `ros_version` (with the same format version) due to this check: https://github.com/ros-infrastructure/rosdistro/blob/df28723d0d2e12b52cd81867d03ed4c979187e3a/src/rosdistro/index.py#L80
Therefore leveling the version of the index format is the cleaner way to go. Then users get a clear error message that they need a new rosdistro version to parse the new format.
This will pave the path to reintegrate the [forked ROS 2 rosdistro](https://github.com/ros2/rosdistro) into the [ROS (1) rosdistro repo](https://github.com/ros/rosdistro/).
=> REP153: adding metadata to the index file

rep-2000.rst
The TODO was about avoiding describing the archive as "fat". This re-words the sentence and removes the TODO.
=> [rep-2000] Resolve TODO about binary archives

rep-0144.rst
This is an pull-request to review and then ratify REP 144. A call for comments will be issued to ros-users@ after some time we'll call for a vote. Please use this PR for comments and voting when the time is appropriate. 
(For reference earlier discussions can be found in PR #94 )
=> Review REP 144

rep-2001.rst
Facilitate default security by including sros2 in the CLI provided through ros-core, or at very least ros-base. Having sros CLI shipped with crystal core packages would helpful when using the official docker images derived from the ros-core and ros-base variants with security.
Related: https://github.com/ros2/variants/pull/10
=> Include sros2 in ros-core

.travis.yml, Makefile, xsd/package_common.xsd, xsd/package_format1.xsd, xsd/package_format2.xsd, xsd/package_format3.xsd, xsdValid.py
As a consequence of REP-149, several elements in the package.xml specification have an added "condition" attribute. This has already been addressed in [rosdep](https://github.com/ros-infrastructure/rosdep/issues/653) and is being addressed in [bloom](https://github.com/ros-infrastructure/bloom/pull/519) but the XSDs needed to be updated for tools like xmllint to be able to validate new package.xml files. This PR addresses those changes.
All package_formatN.xml files validated independently and against existing package.xml files using `xmllint`.
=> Add "condition" Attribute to package_format3.xsd

xsd/package_format3.xsd
The optional file attribute specified in REP-149 [[1]] does not pass
validation without this change. Since the file attribute is new in
format three I did not add the type to package_common.
[1]: http://www.ros.org/reps/rep-0149.html
=> Add LicenseType which supports optional file attribute.

rep-2000.rst
Add clarity to Tier 2 thresholds and help define the support tiers better.
=> Clarify threshold for Tier 2 platforms.

rep-2000.rst
Integration made through [gazebo_ros_pkgs](https://github.com/ros-simulation/gazebo_ros_pkgs/tree/ros2), supporting only Gazebo 9 for Crystal and Dashing.
* **Ubuntu Bionic**: from [official repositories](https://packages.ubuntu.com/bionic/gazebo9)
* **Mac OS**: from [OSRF homebrew tap](https://github.com/osrf/homebrew-simulation/blob/master/Formula/gazebo9.rb#L4) - continuously upgraded
* **Ubuntu Xenial**: from [OSRF packages](http://packages.osrfoundation.org/gazebo/ubuntu-stable/pool/main/g/gazebo9/) - continuously upgraded
* **Debian Stretch**: from [OSRF packages](http://packages.osrfoundation.org/gazebo/debian-stable/pool/main/g/gazebo9/) - continuously upgraded
=> Gazebo versions for ROS 2

rep-0153.rst
This specifies the semantic of the new key `python_version` introduced in ros-infrastructure/rosdistro#145.
=> add python_version key to REP 153

rep-2000.rst
Since #206 the table fails to render: https://www.ros.org/reps/rep-2000.html#eloquent-elusor-november-2019-november-2020
=> fix table layout

rep-0150.rst
Switch `class_loader` and `cmake_modules` to sort alphabetically.
=> REP 150: Alphabetize packages in the ros_core metapackage

.travis.yml
`xmlschema` 1.1.0 (released Jan 23 2020) dropped support for Python 2. This has been breaking CI builds.
Note that I am explicitly listing the two jobs rather than using Travis' matrix expansion as before, so that we can still get up-to-date versions of `xmlschema` for Python 3 builds.
If you'd prefer to use the same `xmlschema` version for both builds, this PR can be simplified to a just adding: `<1.1` on line 8.
=> Force xmlschema < 1.1 for Python 2

.travis.yml, rep-2004.rst
First commit, haven't read/edited fully yet: 
- rearranged/rewrote abstract and motivation
- removed [ROS Core] points
- numbered requirements
- added DCO to change control level 1
- moved description to rationale
- added reference implementation content
- removed s.o. link
- small edits
Signed-off-by: maryaB-osr <marya@openrobotics.org>
=> REP 2004 extras

rep-2000.rst
TL;DR ROS 2 release schedule post Foxy:
* May 2021: G Turtle: non-LTS release, supported for 1.5 years
* May 2022: H Turtle: LTS release, supported for 5 years
* May 2023: I Turtle: non-LTS release, supported for 1.5 years
* May 2024: J Turtle: LTS release, supported for 5 years
* and so on, alternating annually between LTS and non-LTS releases
=> add release schedule for ROS 2 releases post-Foxy

rep-2004.rst
Reworded platform support section to be ROS 1 inclusive.
Recommend license declaration for level 5.
Signed-off-by: maryaB-osr <marya@openrobotics.org>
=> Review revisions rep-2004

rep-2004.rst
I like this idea but as I was writing it, it felt a bit odd for a couple of reasons:
- There's not an exact 1-to-1 mapping for each item and declaration section, and some of the items don't come up at all, which makes it seem like the template isn't a good representation of the requirements
- To me the template was something people could copy and paste into their own packages. There's no context in the template alone (or in any quality declaration) for those item numbers, though, besides the link to the REP, which might be confusing if people copy and paste and don't remove the numbering scheme from the headings
Signed-off-by: maryaB-osr <marya@openrobotics.org>
=> Add item numbers to quality declaration template

rep-0151.rst
This is a draft of a rewrite of REP 151 now that more information is known about transitioning to Python 3 in ROS Noetic. This replaces PR #149.
=> REP 151 Python 3 rewrite

rep-2000.rst
Support for building rmw-cyclonedds-cpp has been available in meta-ros
for Dashing since Milestone 10 (2020-01-07), so drop the exception for
it not being supported in Dashing.
=> REP-2000: Drop OpenEmbedded exception in rmw_cyclonedds_cpp Dashing support

rep-2005.rst
This PR is my attempt to capture the results of a synchronous discussion on 2020-04-09 of this REP among a volunteer subset of the TSC, specifically @dirk-thomas, @SteveMacenski,  @lokesku, @kyrofa, @ablasdel, and @gbiggs.
With these changes, we aim to address the main open questions from the conversation to date on the REP, primarily:
* Name: `ROS 2 Standard Library` becomes `ROS 2 Common Packages`, which carries less baggage and allows more flexibility.
* Change control: A TSC voting process for merges is introduced.
* Guidance on merging: Qualitative criteria are added to assist reviewers in coming to their own decisions on proposed changes.
* Relationship to distros: The list will be annotated over time to indicate the availability of each package in each distro.
* Relationship REP …
=> Edits following TSC subgroup discussion

rep-2004.rst
https://github.com/ros-infrastructure/rep/pull/218#discussion_r416283618
Signed-off-by: maryaB-osr <marya@openrobotics.org>
=> Adjusting 3.v.b requirement

rep-0128.rst
Mention that CATKIN_IGNORE may be any type of file and its contents are ignored
=> clarify CATKIN_IGNORE may be a file, directory, or (dangling) symlink

.travis.yml, rep-0133.rst, rep-2004.rst
Abstract
========
This REP describes a set of categories which are meant to convey the quality, or at least the maturity, of packages in the ROS ecosystem.
Inclusion in one category or another is based on the policies to which the packages adhere.
The categories are meant to give some expectation as to the quality of a package and allows the maintainers to be more strict with some packages and less so with others.
The purpose of these categories is not to enforce quality, but to set expectations for consumers of the packages and to encourage maintainers of the packages to document how their package's policies achieve that quality level.
The documented policies allow consumers of the packages to consider any caveats for the package or its dependencies when deciding whether or not the …
=> REP-2004: Package Quality Categories

rep-2005.rst
- meta-ros: This is the OpenEmbedded layer for ROS. It is used to build ROS 2 packages for OpenEmbedded Linux and for webOS Open Source Edition.It is actively maintained for ROS 2 (a list of completed and future development milestones is [here](https://github.com/ros/meta-ros/wiki/Superflore-OE-Recipe-Generation-Scheme#milestones)) and is widely used (there are on average 20+ unique clones per day).
- superflore: An extended release manager for ROS. It is used to generate content for meta-ros from the ROS Index.
=> REP 2005: Add meta-ros and superflore

rep-2005.rst
This REP defines a curated list of ROS 2 repositories to provide community members with guidance regarding which parts of the ROS 2 ecosystem are widely used, actively maintained, and of high quality. Furthermore, we encourage contributors to focus their efforts on items from this list.
The naming "Standard Library" is following the same term of the [Python Standard Library](https://docs.python.org/3/library/) (but is up for discussion if a different term is proposed which describes the content better).
=> REP 2005: ROS 2 Common Packages

rep-2002.rst
This is a proposal for a rolling ROS distribution that will make future ROS 2 releases easier to bootstrap.
:scroll: [Rendered rst via GitHub](https://github.com/nuclearsandwich/rep/blob/rep-2002/rep-2002.rst)
=> REP 2002: adding a rolling ROS distribution

rep-2005.rst, rep-2006.rst
This PR adds in REP-2006, which is the Security Vulnerability Disclosure Policy for ROS 2.  The original proposal was drafted by the [ROS 2 Security Working Group](http://wiki.ros.org/ROS2/WorkingGroups/Security), with some further edits by myself and @SidFaber .
We've decided to open this as a REP (rather than just documentation) since it affects all of the ROS 2 Common Packages in REP-2005.  Thus we would like to give the community a chance to weigh in on this policy.
@chapulina @ros2/security_working_group @thomas-moulard FYI.
=> REP-2006: ROS 2 Security Vulnerability Disclosure Policy.

rep-0150.rst
This is to move a GUI dependency out of the robot
metapackage.
Signed-off-by: Chris Lalancette <clalancette@gmail.com>
This goes along with https://github.com/ros/metapackages/pull/30
=> Add joint_state_publisher_gui to REP-150.

rep-0153.rst
This additional semantic distribution_status is suggested in [REP 2002](https://www.ros.org/reps/rep-2002.html#changes-to-rosdistro-distribution-files). #REP
=> REP 0153: Add `rolling` as a well-defined distribution_status.

rep-0126.rst, rep-0132.rst, rep-0136.rst, rep-0137.rst, rep-0141.rst, rep-0143.rst, rep-0153.rst
The Table of contents is in the layout already this was leading to documents with two tables of contents in sequence.
Noticed by @nuclearsandwich
=> Remove the redundant table of contents declarations

rep-2000.rst
Rolling Ridley will potentially always share a target platform with an existing or upcoming stable ROS distribution. This adds a brief entry for it declaring support for the same platforms as Foxy Fitzroy.
=> Add Rolling Ridley to REP 2000.

rep-0149.rst, xsd/package_format3.xsd
Atm literals can't contain single / double quotes and as a result a an empty string can't be expressed, e.g. the following are invalid expressions:
* `$FOO == `
* `$FOO == ''`
* `$FOO == ""`
* (and there is no `not` operator either: `not $FOO`)
The only way to express these conditions atm is to use a certainly undefined variable (which will evaluate to an empty string):
* `$FOO == $UNIQUE_NAME_WHICH_CERTAINLY_DOES_NOT_EXIST_SO_EVALUATES_TO_AN_EMPTY_STRING`
---
This update allows to use single or double quotes to quote literals which allows to represent an empty string as well as strings with arbitrary characters (e.g. spaces or non-alphanumeric).
Considerations:
* Allowing these additional cases doesn't break any existing condition since the newly allowed quoted literals weren't valid …
=> update REP 149 to enable quoted literals in conditions

rep-2005.rst
This is a proposal to add Robot Localization to the REP 2005 common packages definition. ROSCon video can be seen here: https://www.youtube.com/watch?v=nfvvpYBAMww.
This package is the ROS/2 default state estimation and GPS processing vendor in the ecosystem, utilized by Navigation, Autoware, and countless drone, agriculture, and other ROS projects. Really, I think you'd find a hard time finding a robust robot system in ROS that doesn't use it. Basic feature set:
- Odometry sensor fusion
- Global localization technology fusion
- GPS processing and fusion
This package is in my queue alongside Navigation2 and d SLAM Toolbox as a Tier 1 supported package, receiving a response within 24 hours to any new ticket on work days (except questions better suited to ROS Answers, which I immediately …
=> Add R_L to REP 2005

rep-2005.rst
Adding navigation website / documentation source to REP-2005 for TSC contribution tracking. I don't think anyone disagrees the value of supported documentation, so keeping this one short.
=> Adding navigation.ros.org to REP-2005

rep-2005.rst
This is a proposal to add the ROS2 Ouster driver to the REP 2005 common packages definition.
This package is analog to Velodyne drivers and is suitable for a large scope of navigation, autonomous vehicle and general perception tasks. They have been built against a design doc, making use of the modern tools that ROS2 enables including Lifecycle and Components, with serious consideration to performance and soft real-time requirements. It also has the official support of Ouster LIDAR. 
It has a mere 22 stars at the moment, but I think the reuse is clear. Users include Box Robotics @tpanzarella and Rover Robotics @rotu with 2 very active maintainers: Tom and I. 
We have CI setup and run the full suite of ROS2 linters with (what some may consider excessive) documentation on the API, …
=> Proposal to add Ouster ROS2 Drivers

rep-2005.rst
This PR adds the [ros2/rclc repo](https://github.com/ros2/rclc/) to REP-2005, which lists the common packages of ROS 2. Together with the ROS Client Support Library (rcl), the rclc packages shall implement a feature-complete ROS Client Library for the C programming. That is, rclc provides convenience functions for use of rcl types (nodes, subscriptions, services, etc.) and typical client library features that are not provided by rcl itself. Most important, rclc provides an Executor, named rclc Executor, and basic lifecycle support. An interface for parameters is in work.
_Scope:_
* Open source: All packages of rclc come under Apache 2.0 license.
* Connected to the ROS 2 project: rclc directly builds upon the ROS Client Support library (rcl) and aims at adding another feature-complete …
=> Add rclc packages to REP-2005.

rep-2005.rst
Justification:
* Quality Level 1
* Dependency of RCP package `rclcpp`
=> Add libstatistics_collector to REP-2005

.github/workflows/ci.yaml
Travis CI is becoming increasingly unavailable. This ports the same test suite to run via GitHub Actions.
=> Add GitHub Actions worflow for rep CI.

rep-0149.rst
According to the following sources, there is a missing "-" in the Apache license's short identifier.
* https://opensource.org/licenses/Apache-2.0
* https://spdx.org/licenses/Apache-2.0.html
** Why is this important?**
Many packages in ROS2 are using the Apache license. There are potential legal issues in the future if developers are using the wrong short identifier (as I was doing).
=> Correct Apache-2.0 license short identifier

rep-2005.rst
Justification:
* Gaining usage across ecosystem
* Helps packages attain some REP-2004 quality bars easily and freely
* Has its own CI and unit testing
=> Add ros-tooling GitHub Action CI to REP-2005

rep-2000.rst
...which is different from the platforms targeted by Foxy.
=> Rolling now targets the same platfroms as Galactic

rep-0151.rst
Without this change, `shebang` is invisible. Showing how `shebang` looks like seems to be critical in the very context.
Problematic rendering can be seen at [Shebangs and reliance on the Python command](https://www.ros.org/reps/rep-0151.html#shebangs-and-reliance-on-the-python-command) section.
=> [rep-0151] rst not rendering Python shebang code, which is crucial in the context.

rep-2000.rst
That's what we promised in the Release Schedule on top, so we
should honor that.
=> Update the Galactic EOL date to November 2022.

.github/workflows/ci.yaml, rep2html.py
[cgi.escape](https://docs.python.org/3.7/library/cgi.html#cgi.escape) was removed in Python 3.8 after being deprecated since it does not escape quotes by default and is therefore considered unsafe. In order to preserve the current behavior I've added [html.escape](https://docs.python.org/3.7/library/html.html#html.escape) with quote=False in order to match exactly the old behavior and then switched to the default behavior and compared the two.
```diff
--- quote-false/rep-0000.html   2021-05-17 15:38:13.745754117 -0700
+++ quote-true/rep-0000.html    2021-05-17 15:40:07.775869644 -0700
@@ -352,7 +352,7 @@
Meeussen, Wim
Mihelich, Patrick                                mihelich&#32;&#97;t&#32;willowgarage.com
Moulard, Thomas …
```
=> Replace removed cgi.escape with html.escape.

rep-2007.rst
Adds a REP for supporting type adaptation (a.k.a. Type Masquerading) in `rclcpp`.
----
References and related links:
- rclcpp pull request:
- https://github.com/ros2/rclcpp/pull/1557
- Aspirational examples and demos:
- https://github.com/ros2/examples/pull/300
- https://github.com/ros2/demos/pull/482
- Scratch pad for prototyping the technical mechanics for how this will work:
- https://repl.it/@wjwwood/HarmoniousQuaintWorkers#main.cpp (or the repository [here](https://github.com/audrow/MockingRosTypeAdapter))
- older one: https://github.com/audrow/TypeAdaptation
=> REP 2007: Type Adaptation

rep-2005.rst
Add packages maintained by the ros-web working group to REP-2005.
* `rosbridge_suite` is a popular websocket protocol and server for communicating with ROS systems
* `foxglove/ros*` packages are TypeScript libraries for interacting with ROS systems
* `RobotWebTools/*` packages are JavaScript libraries for interacting with ROS systems
As discussed with @emersonknapp.
I have not submitted [Foxglove Studio](https://github.com/foxglove/studio) in this PR - we would like to submit it for consideration at a later date.
These didn't seem to fit under any existing section, so I created a new one. Open to feedback on where they belong.
=> Add ros-web packages to REP-2005

rep-2005.rst
This PR is to update and clean up MoveIt links to point to individual packages ROS Index rather than GitHub
=> Update REP-2005 MoveIt links

rep-0111.rst
The [rosdep/python.yaml](https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml) file contains many rules which resolve only to pip packages. In general, pip is supported on nearly all modern platforms and the rules in that file generally apply to all of them. To ensure that these rules are available to new platforms as they are added and also to those which aren't listed specifically each time a new `-pip` rule is added, I'm proposing support for OS_NAME wildcards in rosdep.
For example, I propose this syntax:
```yaml
python-backoff-pip:
'*':
pip:
packages: [backoff]
```
...rather than the current structure:
```yaml
python-backoff-pip:
arch:
pip:
packages: [backoff]
debian:
pip:
packages: [backoff]
fedora:
pip:
packages: [backoff]
opensuse:
pip:
packages: [backoff]
osx:
pip: …
```
=> Add wildcard OS_NAME to REP 111

rep-2000.rst
We've historically listed the default RMW for the release first in this table.
=> List the default RMW first for Humble in REP 2000

rep-0001.rst
The ros-users@lists.ros.org mailing list does not exist since 2019. REP proposals should be discussed on discourse.ros.org instead.
=> rep-0001: replace ros-users@lists.ros.org by discourse

rep-2001.rst
This goes along with the change to the variants repository
that does the same.
Goes along with https://github.com/ros2/variants/pull/36
=> Add rclcpp_action to REP-2001.

rep-2008.rst, rep-2009.rst
This is a REP to describe a type negotiation feature that is part of a collaboration with Nvidia.
=> REP 2009: Topic Message Type Negotiation Feature

rep-2001.rst
There's a gap in the variants provided by ROS 1 and ROS 2. This PR adds the `perception`, `simulators` and `desktop-full` variants (see [REP-108: desktop variants](https://www.ros.org/reps/rep-0108.html#desktop-variants) and [REP-150: desktop variants](https://ros.org/reps/rep-0150.html#desktop-variants)).
I tried my best to match the ROS 1 variants, as I believe that's what users would expect. But we don't need to strictly follow ROS 1 and should adapt to ROS 2's needs as appropriate. Therefore I'd appreciate feedback on whether we should add or remove packages to the lists on this PR.
Here's a collection of ROS 1 resources:
* [REP-108](https://www.ros.org/reps/rep-0108.html#desktop-variants) (From Diamondback)
* `perception`
* `[image_common, image_transport_plugins, image_pipeline, …
=> REP-2001: Desktop-full, perception and simulation variants for ROS 2 

rep-2001.rst
On #334 I changed "recommended from Humble" to "available from Humble" according to reviewer feedback, but that ended up making things confusing. Aren't `simulation` and `perception` also only available from Humble? (i.e. https://github.com/osrf/docker_images/pull/619#issuecomment-1124132514).
I think it's clearer if the entry-point list doesn't say anything about versions, and instead users can check each version below as needed.
=> REP-2001: Remove confusing comment

rep-2010.rst
Makes data types consistent between ``request_type`` and ``REQUEST_SENT/RECEIVED`` members. 
Originally, the ``request_type`` was using uint8 and the members were using int8. We could have them of the same type for consistency. 
cc @jacobperron
=> Keep data types consistent

rep-2005.rst
We added a new package for parameter support to https://github.com/ros2/rclc/, which is used in micro-ROS.
=> Add rclc_parameter to REP-2005

rep-2005.rst
Adding [bond](https://github.com/ros/bond_core) to REP-2005. It has clear use across a large number of projects for checking that servers are still spinning. There is a basic ROS2 port but could use some work to allow for lifecycle support (https://github.com/ros/bond_core/pull/64) and release into ROS2.
=> Adding bond_core, bondcpp, bondpy to REP 2005

rep-2005.rst
This is a proposal to add the [diagnostic aggregator](https://index.ros.org/p/diagnostic_aggregator/) to the REP 2005 common packages definition.
The diagnostic updater and self test are already part of REP2005 and usually go together with the diagnostic aggregator in a common diagnostic setup.
Signed-off-by: Nordmann Arne (CR/ADT3) <arne.nordmann@de.bosch.com>
=> Adds diagnostic aggregator to REP 2005

rep-2005.rst
The Regulated Pure Pursuit controller enables differential and ackermann steering robots to accurately track backs better than Adaptive Pure Pursuit and nominal Pure Pursuit. It does so without dynamic collision avoidance, a relatively common request among users.
The Smac planner enables Hybrid-A* and soon to be State Lattice planning to allow for kinematically feasible paths to be calculated in real-time to handle non-circular robots utilizing the extents of their proper drivetrains.
=> Adding 2 new Nav2 packages to REP 2005

rep-2005.rst
Remove outdated packages:
- moveit2/moveit_fake_controller_manager which has moved into ros2_control
And to add a new package:
- moveit2/pilz_industrial_motion_planner, a new motion planner
=> Update REP-2005 MoveIt Packages

rep-2005.rst
The VSCode ROS extension supports ROS1 and ROS2 development on Linux and Windows. It does not have any proprietary code or service connections, is actively maintained and cross platform.
=> Propose VSCode ROS extension for REP-2005

rep-0003.rst
Debian Buster is EOL
https://www.debian.org/News/2022/20220910
=> Debian Buster EOL 2022 Sep

rep-0144.rst
Link to browse existing ROS packages http://www.ros.org/browse is outdated, updating it with https://index.ros.org/packages/
=> Update outdated link in REP 144

README.txt, rep-0012.rst, rep-0128.rst
There is no example plaintext REP, every REP is in RST. Remove that language from README (fixing broken PEP link), and remove from REP 12, which points to REP 9 as an example of plaintext, but which REP 9 actually contains ABI Compatibility information.
=> Fix broken references to plaintext reps, and broken link in README

rep-0144.rst
After a conversation about naming of packages that could be generic, but having an entity (project, organization, individual, ...) prefix would be helpful, we agreed in the last ROS 2 meeting to update the language about prefixes in this REP.
I'd like to RFC on this update, with 👍 / 👎's.
I will update the post-date in the header when merging.
=> [REP-144] update language around prefixing entity name to packages

rep-2007.rst
Replace `cv::Map` with `cv::Mat`
=> [REP-2007] Fix typo

rep-0147.rst
The velocity section says the command is acceleration. It's a typo. I discovered it while implementing the velocity control in ArduPilot compliant with REP147.
https://github.com/ArduPilot/ardupilot/pull/24549
=> Fix copy-paste error in velocity control

rep-0155.rst
This PR proposed to change the type of the ROI from the standard [sensor_msgs/RegionOfInterest](https://github.com/ros/common_msgs/blob/noetic-devel/sensor_msgs/msg/RegionOfInterest.msg) to [hri_msgs/NormalizedRegionOfInterest2D](https://github.com/ros4hri/hri_msgs/blob/master/msg/NormalizedRegionOfInterest2D.msg).
The use of a non-standard message is offset by the following advantages:
- checks on normalized values are image independent and more robust
- algorithms which depend only on the faces/bodies relative position/size and not on the source image can avoid subscribing to the camera info just to obtain the source image size
- aligned with [hri_msgs/Skeleton2D](https://github.com/ros4hri/hri_msgs/blob/master/msg/Skeleton2D.msg) which makes use of normalized coordinates too
- …
=> Change ROI message type to hri_msgs/NormalizedRegionOfInterest2D

rep-2003.rst
This is a proposal to formalize the QoS settings for sensor and map data with the goal of making generally compliant drivers and state estimation software
=> REP 2003: Sensor Data and Map QoS Settings

Makefile, genrepindex.py, rep2html.py, xsdValid.py
1.  Removes instances of /usr/bin/env python, which don't work on non-Linux and also were wrong in some cases.
2.  Makes sure to use raw strings for regexes, which gets rid of some warnings with modern Python.
3.  Uses '-f' when removing files to quite warnings.
=> Small cleanups to the REP scripts.

rep-0105.rst
Also, [link 4 at the bottom of the page](https://www.ros.org/reps/rep-0105.html#egm96) takes too long to load, maybe it would be worth changing it.
=> increase readability of rep 105

rep-2001.rst
As a developer I often rely on [colcon mixin](https://github.com/colcon/colcon-mixin-repository) to pass build flags for my projects. For convenience, I'd like to propose adding this package to the `ros-dev-tools` variant. If approved, I can follow up with changes needed to [infra-variants](https://github.com/ros-infrastructure/infra-variants).
=> [REP-2001] Add colcon mixin to ros-dev-tools

rep-2000.rst
Because of various issues, we are stuck on Python 3.8 for both Iron and Jazzy.  Update REP-2000 to reflect this fact.
See https://github.com/ros-infrastructure/ros2-cookbooks/pull/69 for more of the motivation behind this PR.
@Yadunund FYI
=> Update the Python minimum to 3.8 for Iron and Jazzy.

rep-2000.rst
Alternatively, we could remove this line or replace it with something like:
> Rolling Ridley targets the same platforms as the latest (non-Rolling) distribution above.
=> Update reference to Rolling target platforms

rep-2001.rst
It was removed in https://github.com/ros2/demos/pull/701 (since it was a duplicate with some other packages), and then further removed from the variants in https://github.com/ros2/variants/pull/44, so that should be reflected here as well.
@ahcorde FYI
=> Remove action_tutorials_interfaces from the Rolling desktop package.

docutils_transforms_reps.py, rep0/rep.py
Otherwise we can get SyntaxWarnings on modern versions of Python.
=> Fix the regexs in the python code here to be raw strings.

rep-2005.rst
As [discussed](https://docs.google.com/document/d/1TGXYp33N00ZJtilsRzfClFXcSyMa4QKVNmA03Lx9D7w/edit?disco=AAABfJswkzE) on the ROS PMC meeting of March 4th, 2025 we need to update REP 2005 with the changes done on the distributed packages after the name change of Fast DDS from `fastrtps` to `fastdds`.
=> Changes on REP 2005 due to package name change of Fast DDS

.github/workflows/ci.yaml
While we are in here, also update the actions we depend on to their latest versions, and add in pygments to avoid a warning when running the tests.
=> Fix the CI runner to use Ubuntu 24.04.
